group: edge
dist: trusty

env:
  global:
    TERM=dumb

language: java
jdk:
  - openjdk8
  - oraclejdk8

install: true
before_install:
  - sudo apt update
  - sudo apt install -y python-pip
  - sudo pip install httpie
  - sudo kill $(sudo lsof -t -i:8080) | true

script:
  - bash gradlew clean build
  - bash gradlew run &
  - sleep 15
  - http :8080
